name: 'Fork Sync With Upstream'
author: 'Adam Ormsby (@aormsby)'
description: 'Automatically updates fork with new commits from upstream repo, run on an unmodified branch (usually main)'

branding:
  icon: refresh-ccw
  color: orange

inputs:
  github_token:
    description: 'Token for accessing the remote repo with authentication'
    required: false

  upstream_repository:
    description: 'Upstream repository, e.g. => aormsby/Fork-Sync-With-Upstream-action'
    required: true

  upstream_branch:
    description: 'Branch to sync from, default = main'
    required: false
    default: 'main'

  target_branch:
    description: 'Branch to push to, default = main'
    required: false
    default: 'main'

  git_checkout_extra_args:
    description: 'Any extra args to pass to `git checkout` like --recurse-submodules (only used when current branch is not target_branch), default = ""'
    required: false
    default: ''

  git_fetch_extra_args:
    description: 'Any extra args to pass to `git fetch` like --recurse-submodules, default = ""'
    required: false
    default: ''

  git_log_format_args:
    description: 'How to print the list of new commits, default = --pretty=oneline'
    required: false
    default: '--pretty=oneline'

  git_sync_command:
    description: 'Which git command to use for sync (eg "merge --ff-only" or "reset --hard"), default = pull'
    required: false
    default: 'pull'

  git_push_extra_args:
    description: 'Any extra args to pass to `git push` like --force, default = ""'
    required: false
    default: ''

outputs:
  has_new_commits:
    description: 'true when new commits were included in this sync.'

runs:
  using: 'node12'
  main: 'main.js'
